### ISSUE TITLE
Comparison with nix::sys::epoll

### ISSUE THREAD

**Issue by dimbleby** [nathansizemore/epoll#1]
Are you aware of [`nix::sys::epoll`](http://rustdoc.s3-website-us-east-1.amazonaws.com/nix/master/linux/nix/sys/epoll/index.html), repository [here](https://github.com/carllerche/nix-rust)?
- If yes, could you comment on why I would prefer - or not prefer - this or that version of `epoll`?
- If no: well now you are!

Either way, there's no reason that we shouldn't have both, and let the best man win...  If there's a useful comparison to be made, maybe put something in the README?

(Hope this doesn't sound hostile - raising an issue feels like a slightly aggressive way of asking a question - I'm just curious.)

**Comment by nathansizemore** [comment]
Hey-o!

Didn't take it as hostile at all. If I put something in the README, directly comparing it with another's crate - I feel like that just gives the wrong impression of what I'm trying to do with this crate. Have no intention of trying to sell anyone to use this instead of another lib. It's out there because I needed one, wanted to learn, and maybe someone else can benefit from it.

No, I wasn't aware of that repo. I did a search on github, but only came up with projects that looked liked they weren't compiled once 1.0 came out; however, I did just happen upon [this](https://github.com/matildah/koyomi) which appears to be a blatant rip off of that crate, even down to the syntax styling and code structure, which is unfortunate.  Just now getting into Async IO and figured I just write my own, and personally, I like to build everything myself when I learn a new thing!

As far as differences go, there are two: 
1. this crate calls `epoll_create1` while [nix::sys::epoll](http://rustdoc.s3-website-us-east-1.amazonaws.com/nix/master/linux/nix/sys/epoll/index.html) calls [`epoll_create` with a `1024` default size param](https://github.com/carllerche/nix-rust/blob/master/src/sys/epoll.rs#L106), which is now ignored. Is it an advantage? Eh, not really - [`epoll_create`](http://man7.org/linux/man-pages/man2/epoll_create.2.html). There is currently only support for `EPOLL_CLOEXEC` as a param at the moment. It's use does not really apply to all programs, see `O_CLOEXEC` for when this becomes useful [here](http://man7.org/linux/man-pages/man2/open.2.html)
2. This is released under the MPL-2.0 and [nix-rust](https://github.com/carllerche/nix-rust) is MIT.

**Comment by dimbleby** [comment]
Thanks!

The other meaningful difference I spotted is that your `epoll_ctl` requires a `Box<EpollEvent>`, which is a little less convenient and efficient than accepting a reference.  I think this is probably a mistake and you could just as well take a reference..?

All the best.

**Comment by nathansizemore** [comment]
Good point, I dunno why I tend to default to `Box<T>` when interfacing with `T *` in C.
